osx_image: xcode10.2
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/ConfettiView.xcworkspace -scheme ConfettiView-Example -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
deploy:
  provider: script
  script: pod trunk push
  on:
    tags: true
